services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    networks:
      - app-network
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - app-network
networks:
  app-network:
    driver: bridge