services:
  da5402_ai_app:  # This is the service name
    build:
      context: .
      dockerfile: Dockerfile
    container_name: da5402_ai_app 
    ports:
      - "54320:5432"    # PostgreSQL port mapping
      - "18000:18000"   # Custom port mapping
    volumes:
      - .:/app  # Mount local documents/app to container's /app
    tty: true           # Enables command-line access